#!/bin/sh

echo "%%% This file is generated by Makefile."
echo "%%% Do not edit this file!\n%%%"
echo -n "\\def\\githash{"
git rev-parse --short HEAD | tr -d "\n\r"
if ! git diff-index --quiet HEAD; then
    echo -n "*"
fi
echo "}"
